### PR TITLE
use ExecutorService and DeltaSpike to start contexts

### PR DESCRIPTION
**Pull request by StephanSchrader**
- Deployed as single WAR archive
- EJB@Asynchronous still not working due to not started ConversationContext

### CODE REVIEW

**Comment by sebfz1** [comment]
Hi Stephan,

A big thank you for your investigation on this! I will merge it in a new branch and try to understand how it works (with my poor CDI knowledge!). Anyway, you probably have found the reason why we should not hack wicket-cdi as we did, I have to double check this point...

I will try to review this asap and update the users@ thread accordingly...

Thanks again a lot & best regards,
Sebastien.

**Comment by sebfz1** [comment]
Merged into https://github.com/sebfz1/wicket-quickstart-cdi-async/tree/master-schrader

**Comment by sebfz1** [comment]
Hi Stephan,

I confirm you that it works as expected using Apache DeltaSpike (except the EJB@Asynchronous part), without the wicket-cdi-1.1 hack. Congratulations!! :)

I think I better understood how it works, except the `WorkflowProgressListener#onWorkflowProgress(@Observes WorkflowProgress progress)` and the `Event<WorkflowProgress>` but I think there are just there to confuse me because there does not seem to be used... :)

I will cleanup, try to solve the EJB part, and merge to master in the coming days...

Thanks a lot, again,
Sebastien

**Comment by StephanSchrader** [comment]
Hi Sebastien,

The `WorkflowProgress...` event and listener were a try to get around the Wicket websoket behavior. But I had no luck. You can safely delete them.

The EJB part should also work, if you start the session and conversation context.

Have fun :)
Stephan

**Comment by sebfz1** [comment]
Hi Stephan

I did commit changes based on your work in master branch. It was not working when deployed in WildFly directly, so I corrected this. But, after many tentatives, I still cannot get it work with the @Asynchronous.... I will retry later.

Anyway thanks again a lot!

Best regards,
Sebastien.

**Pull request closed without merging**
